# Generated by Django 5.2.3 on 2025-06-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_journalentry_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='narration',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
