# Generated by Django 5.2.3 on 2025-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_journalentryline_narration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
